export const safeProvincesEn = [
  "Rif Dimashq",
  "Dimashq",
  "Damascus",
  "Aleppo",
  "Latakia",
  "Tartus",
  "Idlib",
  "Hama",
  "Homs",
  "Damascus Countryside Governorate",
  "Damascus Governorate",
  "Aleppo Governorate",
  "Latakia Governorate",
  "Tartus Governorate",
  "Idlib Governorate",
  "Hama Governorate",
  "Homs Governorate",
];
export const safeProvincesAr = [
  "ريف دمشق",
  "دمشق",
  "حلب",
  "اللاذقية",
  "طرطوس",
  "إدلب",
  "حماة",
  "حمص",
  "محافظة ريف دمشق",
  "محافظة دمشق",
  "محافظة حلب",
  "محافظة اللاذقية",
  "محافظة طرطوس",
  "محافظة إدلب",
  "محافظة حماة",
  "محافظة حمص"
];
